package pl.scubed.webdoodle.rest;

import java.util.HashSet;
import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("api")
public class CanvasApplication extends Application {
    @Override
    public Set<Class<?>> getClasses() {
        HashSet<Class<?>> hs = new HashSet();
        hs.add(CanvasService.class);
        hs.add(ApplicationConfigService.class);
        return hs;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(pl.scubed.webdoodle.rest.ApplicationConfigService.class);
        resources.add(pl.scubed.webdoodle.rest.CanvasService.class);
    }
}
